### ISSUE TITLE
TypeError: object of type 'Distribution' has no len()

### ISSUE THREAD

**Issue by Jeiyoon** [Yubo02/Wasserstein-K-means-for-clustering-probability-distributions#1]
Hi! Thank you for your great work in advance

I ran your code and found some errors because of the object type 

Errors occurred in the code block below  (DWKM_utils.py):

```python
# Calculate the averaged squared W2 distances for distribution ii to the cluster indexed by groups_ind_0_0.
def sinkhorn_divergence_cluster(groups_ind_0_0, ii, Di):
    dist1=0

    for i in range(len(groups_ind_0_0)):
        dist2 = Di[groups_ind_0_0[i]][ii]
        dist1 = dist1 + dist2
    dist3=dist1/len(groups_ind_0_0)
    return dist3
```

groups_ind_0_0 is Distribution type, so len() and indexing  make errors:

~~~
TypeError: object of type 'Distribution' has no len()
~~~

Thank you

**Comment by Jeiyoon** [comment]
I've  encountered another error in the code block below (DWKM_utils.py):

```python
def partition_into_groups_DWKM(data,Di, groups_ind_0, num_groups):
    groups_ind = [[] for i in range(num_groups)]
    for i in tqdm(range(len(data))):
        min_dist = 10000
        for k in range(len(groups_ind_0)):
            dist = sinkhorn_divergence_cluster(groups_ind_0[k],i,Di)

            if dist < min_dist:
                tmp_c = k
                min_dist = dist

        groups_ind[tmp_c].append(i)
    return groups_ind
```

~~~
Traceback (most recent call last):
  File "MY_PATH/Sinkhorn-Barycenters/Main.py", line 122, in <module>
    groups_ind =  partition_into_groups_DWKM(distrib,Distance_mat0, groups_ind, num_groups)
  File "MY_PATH/Sinkhorn-Barycenters/DWKM_utils.py", line 83, in partition_into_groups_DWKM
    groups_ind[tmp_c].append(i)
IndexError: list index out of range
~~~

**Comment by Yubo02** [comment]
Hi,

Thanks for your feedback!

For the first question: Actually, groups_ind_0_0 is array or vector including all the index of data for group k.

For the second question: I am not sure if your input length makes sense. Please notice groups_ind_0 is the k partition of the {1,...,n}, e.g., if we have total n=10 data and K=2, groups_ind_0 could have the form [[1,2,3],[4,5,6,7,8,9,10]].


Hope that helps.


Best,
Yubo
________________________________

**Comment by Jeiyoon** [comment]
I didn't change anything which means 

I just cloned your Github and ran Main.py with predefined dataset and settings

And then it didn't work


<img width="839" alt="Capture" src="https://user-images.githubusercontent.com/56618962/196828978-e8e2e585-2049-44d1-9ec5-f562da47a7c2.PNG">


Here are details about "group_ind_0_0"

Are they right values?   

First error occurred because "group_ind_0_0" is "Distribution" object

**Comment by Yubo02** [comment]
I see the issues here. The initialization function partition_into_groups should be modified (so that the output would be index) based the code of https://github.com/GiulsLu/Sinkhorn-Barycenters. Sorry for the confusion. I uploaded the new files and hope that will work.

Thanks a lot for your feedback and please let us know if there is any issue!


Best,
Yubo

[https://opengraph.githubassets.com/7b7239edb424845a8c11b2eebdc2e4fb7d7ccdcff835f107781b81ef95252949/GiulsLu/Sinkhorn-Barycenters]<https://github.com/GiulsLu/Sinkhorn-Barycenters>
GitHub - GiulsLu/Sinkhorn-Barycenters: Sinkhorn Barycenters via Frank-Wolfe algorithm<https://github.com/GiulsLu/Sinkhorn-Barycenters>
Sinkhorn Barycenters via Frank-Wolfe algorithm. Contribute to GiulsLu/Sinkhorn-Barycenters development by creating an account on GitHub.
github.com

________________________________

**Comment by Jeiyoon** [comment]
It works! Thank you so much 😊 

Your motivation and idea are really impressive!

Thank you!
